### ISSUE TITLE
callback in fragment

### ISSUE THREAD

**Issue by martialDevOrange** [ravi8x/Barcode-Reader#1]
Hi,

i use your library in a fragment that implements BarcodeReader.BarcodeReaderListener, but your code search for listener in the Main Activity... 
How to use it directly from fragment ?

**Comment by ravi8x** [comment]
@martialowt I have updated the example project by including Fragment integration. Please check these examples.

`BarcodeFragment.java` and `BarcodeFragmentTestActivity.java`
https://github.com/ravi8x/Barcode-Reader/tree/master/example/src/main/java/info/androidhive/barcodereader

Also you need to use latest version of the library i.e `1.1.3`

**Comment by martialDevOrange** [comment]
Thanks, it's ok, it works now  :-)

I have 2 requests if possible:
- add option to choose between front or back camera
- adding start/stop methods (or pause/resume) to ScanOverlay : because when a barcode is detected I stop scanning but the overlay continue to move

and thanks again for your Library and your support

**Comment by ravi8x** [comment]
Okay. I'll consider your suggestions. However you are free to fork the repo and do the changes. I'll release them in next version.

Thank You
