### ISSUE TITLE
Camera screen always black on first run of the app

### ISSUE THREAD

**Issue by Zookey** [ravi8x/Barcode-Reader#2]
Hi,

It seems that Camera permission is not working fine. When you run the app for first time you will always get black screen even approving Camera permission.

**Comment by camendoza94** [comment]
https://stackoverflow.com/a/33080682/5975643 this could be a reason

**Comment by orogersilva** [comment]
There is a pending pull request for it. #6

**Comment by ravi8x** [comment]
This is fixed in `1.1.5`.
