### ISSUE TITLE
Backward compatibility 

### ISSUE THREAD

**Issue by karanchapaneri** [ravi8x/Barcode-Reader#3]
I am having API 25, and on this level, the library doesn't seem to work. Seems to be a backward compatibility issue

**Comment by ravi8x** [comment]
Do you have any error log or something to support your statement? That would be helpful in further debugging.

**Comment by uncommonaman** [comment]
Couldn't compile it against api 25. Downloadin sdk 26 now. But does that mean it is not going to work on devices with api level lower than 26?

**Comment by ravi8x** [comment]
It will work.
