### ISSUE TITLE
Green color in right side of camera preview

### ISSUE THREAD

**Issue by sivasankar0457** [ravi8x/Barcode-Reader#35]
@ravi8x Ravi
Hi,Please let me how to solve this issue if possible.If fragment is resizing green color in right side of camera preview.

**Comment by IanWambai** [comment]
Also having this issue

**Comment by sivasankar0457** [comment]
IanWambai, I solved this issue

**Comment by IanWambai** [comment]
How did you solve it?

**Comment by sivasankar0457** [comment]
In BarcodeScannerView Class replace method with below code 

public synchronized Rect getFramingRectInPreview(int previewWidth, int previewHeight) {
       if (mFramingRectInPreview == null) {
           Rect framingRect = mViewFinderView.getFramingRect();
           int viewFinderViewWidth = mViewFinderView.getWidth();
           int viewFinderViewHeight = mViewFinderView.getHeight();
           if (framingRect == null || viewFinderViewWidth == 0 || viewFinderViewHeight == 0) {
               return null;
           }
           Rect rect = new Rect(framingRect);
           if(previewWidth < viewFinderViewWidth) {
               rect.left = rect.left * previewWidth / viewFinderViewWidth;
               rect.right = rect.right * previewWidth / viewFinderViewWidth;
           }
           if(previewHeight < viewFinderViewHeight) {
               rect.top = rect.top * previewHeight / viewFinderViewHeight;
               rect.bottom = rect.bottom * previewHeight / viewFinderViewHeight;
           }
           mFramingRectInPreview = rect;
       }
       return mFramingRectInPreview;
   }

**Comment by mkansara** [comment]
The file and method name not exist.
