### ISSUE TITLE
Any chance to get this for SDK 25?

### ISSUE THREAD

**Issue by gnomium** [ravi8x/Barcode-Reader#5]

**Comment by ravi8x** [comment]
Whats the problem in using it with SDK 25? The library already has **targetSdkVersion 26**.

**Comment by gnomium** [comment]
i can not use it for my project since i have other dependencies which are not compatible with 26.
what would be necessary to downgrade it to 25?

**Comment by ravi8x** [comment]
As we always target to latest version, 26 is kept as targetSdkVersion. You can fork the library and do the necessary changes.
